---
title: EvalError
slug: Web/JavaScript/Reference/Global_Objects/EvalError
tags:
  - Error
  - EvalError
  - JavaScript
  - Reference
translation_of: Web/JavaScript/Reference/Global_Objects/EvalError
---
<div>{{JSRef("Global_Objects", "Error", "EvalError,InternalError,RangeError,ReferenceError,SyntaxError,TypeError,URIError")}}</div>

<h2 id="Summary">Сводка</h2>
<p>Объект <strong><code>EvalError</code></strong> представляет ошибку, возникающую в глобальной функции {{jsxref("Global_objects/eval()", "eval()")}}.</p>

<h2 id="Syntax">Синтаксис</h2>
<pre class="syntaxbox"><code>new EvalError([<var>message</var>[, <var>fileName</var>[, <var>lineNumber</var>]]])</code></pre>

<h3 id="Parameters">Параметры</h3>
<dl>
 <dt><code>message</code></dt>
 <dd>Необязательный параметр. Человеко-читаемое описание ошибки.</dd>
 <dt><code>fileName</code> {{non-standard_inline}}</dt>
 <dd>Необязательный параметр. Имя файла, содержащего код, вызвавший исключение.</dd>
 <dt><code>lineNumber</code> {{non-standard_inline}}</dt>
 <dd>Необязательный параметр. Номер строки кода, вызвавшей исключение.</dd>
</dl>

<h2 id="Description">Описание</h2>
<p>Исключение <code>EvalError</code> выбрасывается при неправильном использовании глобальной функции {{jsxref("Global_objects/eval()", "eval()")}}.</p>

<h2 id="Properties">Свойства</h2>
<dl>
 <dt>{{jsxref("EvalError.prototype")}}</dt>
 <dd>Позволяет добавлять свойства в объект <code>EvalError</code>.</dd>
</dl>

<h2 id="Methods">Методы</h2>
<p>Глобальный объект <code>EvalError</code> не содержит собственных методов, однако, он наследует некоторые методы из цепочки прототипов.</p>

<h2 id="EvalError_instances">Экземпляры объекта <code>EvalError</code></h2>

<h3 id="Properties_2">Свойства</h3>
<div>{{page('/ru/Web/JavaScript/Reference/Global_Objects/EvalError/prototype', 'Properties')}}</div>

<h3 id="Methods_2">Методы</h3>
<div>{{page('/ru/Web/JavaScript/Reference/Global_Objects/EvalError/prototype', 'Methods')}}</div>

<h2 id="Examples">Примеры</h2>
<p>Объект <code>EvalError</code> в настоящий момент не используется и он никогда не выбрасывается в процессе выполнения.</p>

<h3 id="Example:_Create_an_EvalError">Пример: создание экземпляра объекта <code>EvalError</code></h3>
<pre class="brush: js">try {
  throw new EvalError('Привет', 'someFile.js', 10);
} catch (e) {
  console.log(e instanceof EvalError); // true
  console.log(e.message);              // "Привет"
  console.log(e.name);                 // "EvalError"
  console.log(e.fileName);             // "someFile.js"
  console.log(e.lineNumber);           // 10
  console.log(e.columnNumber);         // 0
  console.log(e.stack);                // "@Scratchpad/2:2:9\n"
}
</pre>

<h2 id="Specifications">Спецификации</h2>
<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Спецификация</th>
   <th scope="col">Статус</th>
   <th scope="col">Комментарии</th>
  </tr>
  <tr>
   <td>ECMAScript 3-е издание.</td>
   <td>Стандарт</td>
   <td>Изначальное определение.</td>
  </tr>
  <tr>
   <td>{{SpecName('ES5.1', '#sec-15.11.6.1', 'EvalError')}}</td>
   <td>{{Spec2('ES5.1')}}</td>
   <td>Не используется в этой спецификации. Присутствует для обратной совместимости.</td>
  </tr>
  <tr>
   <td>{{SpecName('ES6', '#sec-native-error-types-used-in-this-standard-evalerror', 'EvalError')}}</td>
   <td>{{Spec2('ES6')}}</td>
   <td>Не используется в этой спецификации. Присутствует для обратной совместимости.</td>
  </tr>
 </tbody>
</table>

<h2 id="Browser_compatibility">Совместимость с браузерами</h2>
<p>{{Compat}}</p>

<h2 id="See_also">Смотрите также</h2>
<ul>
 <li>{{jsxref("Error")}}</li>
 <li>{{jsxref("EvalError.prototype")}}</li>
 <li>{{jsxref("Global_objects/eval", "eval()")}}</li>
</ul>
