---
title: AggregateError
slug: Web/JavaScript/Reference/Global_Objects/AggregateError
translation_of: Web/JavaScript/Reference/Global_Objects/AggregateError
---
<blockquote>
<p>{{JSRef}}{{Draft}}{{SeeCompatTable}}</p>
</blockquote>

<p><code><strong>AggregateError</strong></code>当多个错误​​需要包装在一个错误中时，该对象表示一个错误。</p>

<h2 id="语法">语法</h2>

<pre class="syntaxbox">new AggregateError(errors[, message])</pre>

<h3 id="参数">参数</h3>

<dl>
 <dt><code>errors</code></dt>
 <dd>错误的描述，默认为空。</dd>
 <dt><code>message</code>{{Optional_Inline}}</dt>
 <dd>AggregateError错误的提示信息。</dd>
</dl>

<h2 id="描述">描述</h2>

<p>一个<code>AggregateError</code>当需要由操作报告多个错误被抛出，例如通过<a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any"><code>Promise.any()</code></a>，在传递给它的所有<a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any"><code>Promise</code></a>拒绝。</p>

<h2 id="属性">属性</h2>

<dl>
 <dt><code>AggregateError.prototype</code></dt>
 <dd><code>AggregateError</code>的原型</dd>
</dl>

<h2 id="AggregateError_实例">AggregateError 实例</h2>

<h3 id="实例属性">实例属性</h3>

<dl>
 <dt><code>AggregateError.prototype.constructor</code></dt>
 <dd>指定创建实例原型的函数。</dd>
 <dt>{{JSxRef("Error.prototype.message", "AggregateError.prototype.message")}}</dt>
 <dd>错误消息，默认为<code>""</code>。</dd>
 <dt>{{JSxRef("Error.prototype.name", "AggregateError.prototype.name")}}</dt>
 <dd>错误名称，默认为<code>"AggregateError"</code>。</dd>
</dl>

<h2 id="示例">示例</h2>

<h3 id="捕获一个AggregateError">捕获一个AggregateError</h3>

<pre class="brush: js;">Promise.any([
  Promise.reject(new Error("some error")),
]).catch(e =&gt; {
  console.log(e instanceof AggregateError); // true
  console.log(e.message);                   // "All Promises rejected"
  console.log(e.name);                      // "AggregateError"
  console.log(e.errors);                    // [ Error: "some error" ]
});
</pre>

<h3 id="创建一个AggregateError">创建一个AggregateError</h3>

<pre class="brush: js;">try {
  throw new AggregateError([
    new Error("some error"),
  ], 'Hello');
} catch (e) {
  console.log(e instanceof AggregateError); // true
  console.log(e.message);                   // "Hello"
  console.log(e.name);                      // "AggregateError"
  console.log(e.errors);                    // [ Error: "some error" ]
}
</pre>

<h2 id="规范">规范</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Specification</th>
   <th scope="col">Status</th>
   <th scope="col">Comment</th>
  </tr>
  <tr>
   <td><a href="https://tc39.es/proposal-promise-any/#sec-aggregate-error-constructor">ESNext Promise.any Proposal</a></td>
   <td>Stage 3 Draft</td>
   <td>Initial definition.</td>
  </tr>
 </tbody>
</table>

<h2 id="浏览器兼容性">浏览器兼容性</h2>

<div>


<p>{{Compat("javascript.builtins.AggregateError")}}</p>
</div>

<h2 id="相关链接">相关链接</h2>

<ul>
 <li>{{JSxRef("Error")}}</li>
</ul>
